/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */
package io.camunda.migration.diagram.converter;

import java.util.HashSet;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.WeakHashMap;
import java.util.concurrent.ThreadLocalRandom;
import org.camunda.bpm.model.xml.instance.DomDocument;

/**
 * Utility class for generating unique BPMN element IDs.
 *
 * <p>Follows the same ID format as bpmn-js: {@code TypeName_randomSuffix} (e.g., {@code
 * ConditionalEventDefinition_a1b2c3d}).
 *
 * <p>Used when migrating from Camunda 7 to 8 where certain IDs are optional in C7 but required in
 * C8.
 *
 * <p>Each document gets its own instance to track generated IDs and ensure uniqueness.
 */
public final class BpmnIdGenerator {

  static final String ALPHANUMERIC = "0123456789abcdefghijklmnopqrstuvwxyz";
  static final int SUFFIX_LENGTH = 7;

  /** Cache of generators per document. Uses WeakHashMap so generators are GC'd with documents. */
  private static final Map<DomDocument, BpmnIdGenerator> INSTANCES = new WeakHashMap<>();

  /** Set of IDs that have been generated by this instance. */
  private final Set<String> generatedIds = new HashSet<>();

  /** The document this generator is associated with. */
  private final DomDocument document;

  /** Random generator for suffix generation. */
  private final Random random;

  private BpmnIdGenerator(DomDocument document, Random random) {
    this.document = document;
    this.random = random;
  }

  /**
   * Gets or creates a BpmnIdGenerator instance for the given document.
   *
   * @param document the BPMN document
   * @return the generator instance for this document
   */
  public static synchronized BpmnIdGenerator getInstance(DomDocument document) {
    return INSTANCES.computeIfAbsent(
        document, doc -> new BpmnIdGenerator(doc, ThreadLocalRandom.current()));
  }

  /**
   * Creates a BpmnIdGenerator instance with a custom Random.
   *
   * @param document the BPMN document
   * @param random the random generator to use
   * @return a new generator instance (not cached)
   */
  static BpmnIdGenerator createWithRandom(DomDocument document, Random random) {
    return new BpmnIdGenerator(document, random);
  }

  /**
   * Generates a unique ID for the given element type.
   *
   * @param elementType the element type name (e.g., "ConditionalEventDefinition")
   * @return a unique ID in the format {@code TypeName_randomSuffix}
   */
  public String generateUniqueId(String elementType) {
    String prefix = elementType + "_";
    String id;
    do {
      id = prefix + generateRandomSuffix();
    } while (isIdInUse(id));

    generatedIds.add(id);
    return id;
  }

  /**
   * Checks if an ID is already in use, either in the document or among generated IDs.
   *
   * @param id the ID to check
   * @return true if the ID is already in use
   */
  private boolean isIdInUse(String id) {
    // Check if we've already generated this ID
    if (generatedIds.contains(id)) {
      return true;
    }
    // Check if it exists in the original document
    return document.getElementById(id) != null;
  }

  private String generateRandomSuffix() {
    StringBuilder sb = new StringBuilder(SUFFIX_LENGTH);
    for (int i = 0; i < SUFFIX_LENGTH; i++) {
      sb.append(ALPHANUMERIC.charAt(random.nextInt(ALPHANUMERIC.length())));
    }
    return sb.toString();
  }

  /** Clears all cached instances. */
  public static synchronized void clearInstances() {
    INSTANCES.clear();
  }
}
