name: Setup Maven
description: |
  Maven wrapper to abstract defaults for setting maven up
inputs:
  camunda-nexus:
    description: |
      If enabled, Camunda Nexus will be configured and used as a mirror for Maven repositories
      Camunda Nexus is automatically disabled for fork PRs.
    required: false
    default: "true"
  java-version:
    description: Java version to be used
    required: false
    default: '21'
  distribution:
    description: Java distribution to be used
    required: false
    default: 'temurin'
  maven-mirrors:
    description: |
      JSON list of extra Maven mirrors.
      It will be merged with Camunda Nexus settings (if enabled ), with precedence."
    required: false
    default: '[]'
  maven-servers:
    description: |
      JSON list of extra Maven servers.
      It will be merged with Camunda Nexus settings (if enabled), with precedence."
    required: false
    default: '[]'
  maven-version:
    description: Maven version to be used
    required: false
    default: '3.8.6'
  vault-address:
    description: Vault URL to retrieve secrets from
    required: false
  vault-role-id:
    description: Vault Role ID to use
    required: false
  vault-secret-id:
    description: Vault Secret ID to use
    required: false
runs:
  using: composite
  steps:
  - name: Import secrets
    id: secrets
    uses: hashicorp/vault-action@79632e33d6953d190b940ffa440bf97821cabd80
    with:
      url: ${{ inputs.vault-address }}
      method: approle
      roleId: ${{ inputs.vault-role-id }}
      secretId: ${{ inputs.vault-secret-id }}
      secrets: |
        secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_USR;
        secret/data/products/cambpm/ci/nexus NEXUS_APP_CAMUNDA_COM_PSW;
  - name: Setup Java
    uses: actions/setup-java@v5
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.distribution }}
      cache: "maven"
  - name: Setup Maven
    uses: stCarolas/setup-maven@v5
    with:
      maven-version: ${{ inputs.maven-version }}
 # Camunda Nexus and extra mirrors/servers must be merged on ids (extra values have precedence).
  - name: Get Maven mirrors and servers to use
    id: maven
    env:
      # Camunda Nexus is disabled for fork PRs
      CAMUNDA_NEXUS_ENABLED: >-
        ${{
          steps.is-fork.outputs.is-fork != 'true' &&
          inputs.camunda-nexus == 'true'
        }}
      CAMUNDA_NEXUS_MAVEN_MIRROR: >-
        [{
          "id": "camunda-nexus",
          "name": "Camunda Nexus",
          "url": "https://repository.nexus.camunda.cloud/content/groups/internal/",
          "mirrorOf": "*"
        }]
      CAMUNDA_NEXUS_MAVEN_SERVER: >-
        [{
          "id": "camunda-nexus",
          "username": "${{ steps.secrets.outputs.NEXUS_APP_CAMUNDA_COM_USR }}",
          "password": "${{ steps.secrets.outputs.NEXUS_APP_CAMUNDA_COM_PSW }}"
        }]
      EXTRA_MAVEN_MIRRORS: ${{ inputs.maven-mirrors }}
      EXTRA_MAVEN_SERVERS: ${{ inputs.maven-servers }}
    run: |
      # If Camunda Nexus is disabled, reset default mirrors/servers to empty lists
      if [ "${CAMUNDA_NEXUS_ENABLED}" != "true" ]; then
        CAMUNDA_NEXUS_MAVEN_MIRROR="[]"
        CAMUNDA_NEXUS_MAVEN_SERVER="[]"
      fi

      # Use jq 'add' operator to merge grouped sublists
      mirrors=$(\
        jq -n \
        --argjson nexus_mirror "${CAMUNDA_NEXUS_MAVEN_MIRROR}" \
        --argjson maven_mirrors "${EXTRA_MAVEN_MIRRORS}" \
        '[ $nexus_mirror + $maven_mirrors | group_by(.id)[] | add ]'
      )
      servers=$(\
        jq -n \
        --argjson nexus_server "${CAMUNDA_NEXUS_MAVEN_SERVER}" \
        --argjson maven_servers "${EXTRA_MAVEN_SERVERS}" \
        '[ $nexus_server + $maven_servers | group_by(.id)[] | add ]'
      )

      echo mirrors=$mirrors >> $GITHUB_OUTPUT
      echo servers=$servers >> $GITHUB_OUTPUT
    shell: bash
  - name: Update Maven settings.xml
    uses: s4u/maven-settings-action@v4.0.0
    with:
      githubServer: false
      servers: ${{ steps.maven.outputs.servers }}
      mirrors: ${{ steps.maven.outputs.mirrors }}
