/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */

import { execSync } from 'child_process';

/**
 * Global setup that runs before all tests.
 * Waits for the data migration to complete before allowing tests to start.
 * Note: docker-compose.yml is generated by Maven resource filtering during build.
 */
const migrationTimeoutSeconds = Number(process.env.E2E_MIGRATION_TIMEOUT_SECONDS ?? '600');
const checkIntervalSeconds = 2;

async function globalSetup() {
  console.log(
    `Global Setup: Waiting for migration to complete (timeout: ${migrationTimeoutSeconds}s)...`
  );

  let elapsed = 0;

  while (elapsed < migrationTimeoutSeconds) {
    try {
      // Check docker logs for migration completion message
      const logs = execSync('docker compose logs data-migrator 2>/dev/null', {
        encoding: 'utf-8',
        stdio: 'pipe'
      });

      if (logs.includes('Migration completed - test data ready')) {
        console.log('Global Setup: ✓ Migration completed! Tests can now run.');
        return;
      }
    } catch (error) {
      // Container might not be running yet, continue waiting
    }

    // Wait before checking again
    await new Promise(resolve => setTimeout(resolve, checkIntervalSeconds * 1000));
    elapsed += checkIntervalSeconds;

    // Log progress every 10 seconds
    if (elapsed % 10 === 0) {
      console.log(`Global Setup: Still waiting for migration... (${elapsed}s elapsed)`);
    }
  }

  try {
    const status = execSync('docker compose ps', {
      encoding: 'utf-8',
      stdio: 'pipe'
    });
    console.log(`Global Setup: docker compose ps at timeout:\n${status}`);
  } catch (error) {
    console.log('Global Setup: Unable to capture docker compose ps output at timeout.');
  }

  try {
    const logs = execSync('docker compose logs --tail 200 data-migrator', {
      encoding: 'utf-8',
      stdio: 'pipe'
    });
    console.log(`Global Setup: data-migrator logs at timeout:\n${logs}`);
  } catch (error) {
    console.log('Global Setup: Unable to capture data-migrator logs at timeout.');
  }

  throw new Error(
    `Global Setup: Timeout waiting for migration to complete after ${migrationTimeoutSeconds}s`
  );
}

export default globalSetup;

