/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Camunda License 1.0. You may not use this file
 * except in compliance with the Camunda License 1.0.
 */

import { execSync } from 'child_process';

/**
 * Global setup that runs before all tests.
 * Waits for the data migration to complete before allowing tests to start.
 * Note: docker-compose.yml is generated by Maven resource filtering during build.
 */
async function globalSetup() {
  console.log('Global Setup: Waiting for migration to complete...');

  const timeout = 300; // 5 minutes max wait
  const checkInterval = 2; // Check every 2 seconds
  let elapsed = 0;

  while (elapsed < timeout) {
    try {
      // Check docker logs for migration completion message
      const logs = execSync('docker compose logs data-migrator 2>/dev/null', {
        encoding: 'utf-8',
        stdio: 'pipe'
      });

      if (logs.includes('Migration completed - test data ready')) {
        console.log('Global Setup: ✓ Migration completed! Tests can now run.');
        return;
      }
    } catch (error) {
      // Container might not be running yet, continue waiting
    }

    // Wait before checking again
    await new Promise(resolve => setTimeout(resolve, checkInterval * 1000));
    elapsed += checkInterval;

    // Log progress every 10 seconds
    if (elapsed % 10 === 0) {
      console.log(`Global Setup: Still waiting for migration... (${elapsed}s elapsed)`);
    }
  }

  throw new Error(`Global Setup: Timeout waiting for migration to complete after ${timeout}s`);
}

export default globalSetup;

