#!/bin/bash
set -e

echo "Starting Docker Compose services..."
# Note: docker-compose.yml is generated by Maven (mvn process-resources)

# Start docker compose in the background
docker compose up -d

echo "Waiting for migration to complete..."

# Wait for the migration completion message
timeout=300  # 5 minutes max wait
elapsed=0

while [ $elapsed -lt $timeout ]; do
  # Check logs for the completion message
  if docker compose logs data-migrator 2>/dev/null | grep -q "Migration completed - test data ready"; then
    echo "✓ Migration completed! Test data is ready."
    break
  fi

  # Check if the container is still running
  if ! docker compose ps data-migrator --format json 2>/dev/null | grep -q "running\|exited"; then
    echo "Warning: data-migrator container not found or not started yet"
    docker compose logs data-migrator
  fi

  sleep 2
  elapsed=$((elapsed + 2))

  if [ $((elapsed % 10)) -eq 0 ]; then
    echo "Still waiting for migration... (${elapsed}s elapsed)"
  fi
done

if [ $elapsed -ge $timeout ]; then
  echo "ERROR: Timeout waiting for migration to complete"
  docker compose logs data-migrator
  exit 1
fi

# Keep the script running to maintain docker compose
echo "Services are ready. Keeping containers running..."
tail -f /dev/null
